/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as FocusSessionRouteImport } from './routes/focus.session'
import { Route as VaultRockIdRouteImport } from './routes/vault.$rockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSessionRoute = FocusSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => FocusRoute,
} as any)
const VaultRockIdRoute = VaultRockIdRouteImport.update({
  id: '/$rockId',
  path: '/$rockId',
  getParentRoute: () => VaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus': typeof FocusRouteWithChildren
  '/insights': typeof InsightsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRouteWithChildren
  '/focus/session': typeof FocusSessionRoute
  '/vault/$rockId': typeof VaultRockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus': typeof FocusRouteWithChildren
  '/insights': typeof InsightsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRouteWithChildren
  '/focus/session': typeof FocusSessionRoute
  '/vault/$rockId': typeof VaultRockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus': typeof FocusRouteWithChildren
  '/insights': typeof InsightsRoute
  '/missions': typeof MissionsRoute
  '/profile': typeof ProfileRoute
  '/vault': typeof VaultRouteWithChildren
  '/focus/session': typeof FocusSessionRoute
  '/vault/$rockId': typeof VaultRockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/focus'
    | '/insights'
    | '/missions'
    | '/profile'
    | '/vault'
    | '/focus/session'
    | '/vault/$rockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/focus'
    | '/insights'
    | '/missions'
    | '/profile'
    | '/vault'
    | '/focus/session'
    | '/vault/$rockId'
  id:
    | '__root__'
    | '/'
    | '/focus'
    | '/insights'
    | '/missions'
    | '/profile'
    | '/vault'
    | '/focus/session'
    | '/vault/$rockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusRoute: typeof FocusRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  MissionsRoute: typeof MissionsRoute
  ProfileRoute: typeof ProfileRoute
  VaultRoute: typeof VaultRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/session': {
      id: '/focus/session'
      path: '/session'
      fullPath: '/focus/session'
      preLoaderRoute: typeof FocusSessionRouteImport
      parentRoute: typeof FocusRoute
    }
    '/vault/$rockId': {
      id: '/vault/$rockId'
      path: '/$rockId'
      fullPath: '/vault/$rockId'
      preLoaderRoute: typeof VaultRockIdRouteImport
      parentRoute: typeof VaultRoute
    }
  }
}

interface FocusRouteChildren {
  FocusSessionRoute: typeof FocusSessionRoute
}

const FocusRouteChildren: FocusRouteChildren = {
  FocusSessionRoute: FocusSessionRoute,
}

const FocusRouteWithChildren = FocusRoute._addFileChildren(FocusRouteChildren)

interface VaultRouteChildren {
  VaultRockIdRoute: typeof VaultRockIdRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultRockIdRoute: VaultRockIdRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRouteWithChildren,
  InsightsRoute: InsightsRoute,
  MissionsRoute: MissionsRoute,
  ProfileRoute: ProfileRoute,
  VaultRoute: VaultRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
